### ISSUE TITLE
A List 210 Gujarati Stop Words

### ISSUE THREAD

**Issue by BChandrakant** [quanteda/stopwords#11]
If there are stop words of Gujarati language in packages quanteda and stopwords, then they can be useful for text analysis in Gujarati also. Prof. Kenneth Benoit suggested this website for Gujarati stop words: https://github.com/gujarati-ir/Gujarati-Stop-Words. There is available a list of 90 Gujarati stop words on the website. Total 12 'words' were not stop words in the list. Out of those 12 'words', four were uncommon Gujarati words, three words were with incorrect spellings (included in the list of 210 sop words after correction), and five were not words, but they were suffixes for different cases of Gujarati language. A table of 12 excluded 'words is attached herewith. Remaining 78 words were found to be appropriate as stop words in Gujarati. I added 132 Gujarati stop words after studying some Gujarati texts. A list of 210 Gujarati stop words is also attached here. Stop words are arranged in the order of Gujarati dictionary in the list and 78 words are bold faced in it which were available from the said website and were found appropriate as stop words.
I humbly request to Prof. Benoit to add these 210 Gujarati stop words in the packages if they are suitable.
BChandrakant (That is Chandrakant Bhogayata !)
[A List of 210 Gujarati Stop Words.txt](https://github.com/quanteda/stopwords/files/2719155/A.List.of.210.Gujarati.Stop.Words.txt)
[Table of 12 Words Excluded from Stop Words.txt](https://github.com/quanteda/stopwords/files/2719156/Table.of.12.Words.Excluded.from.Stop.Words.txt)

**Comment by kbenoit** [comment]
Thanks @BChandrakant, in PR #13 I have added these under the "misc" source.

I was not 100% sure what you meant with the two files linked above, so I have only added the 210 words from the file `A List of 210 Gujarati Stop Words.txt`.  (I was not sure if the second file, `Table of....txt` was for information only or not.) Can you please review the list in 
https://github.com/quanteda/stopwords/pull/13/files#diff-ee408b3eb40f9d57cce6b37b82cd779c and let me know if I need to modify any of those?
