### ISSUE TITLE
Allow for more intuitive way of removing stopwords from list

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/stopwords#14]
One of the most frequent questions I receive at seminars or workshops is how to add or remove stopwords to/from the lists of this package. While the code for adding stopwords is straightforward, (at least to me) it appears that removing stopwords is not that intuitive. 

What do you think: is it worth it to add a wrapper for the removal of stopwords and add it to this package? Below I show two options that came to my mind.

```r
library(stopwords)
library(magrittr)

# add feature to stopword list
stopw_extended <- c(stopwords("de"), "dass")

"dass" %in% stopwords("de")
#> [1] FALSE

"dass" %in% stopw_extended
#> [1] TRUE

# remove feature from stopword list (works, but the code not very intuitive)
stopw_reduced <- stopwords("de")[!stopwords("de") %in% c("daß", "zu")]

"daß" %in% stopwords("de")
#> [1] TRUE

"daß" %in% stopw_reduced
#> [1] FALSE

# possible wrappers
stopw_reduced <- c(stopwords("de"), -c("daß", "zu"))

stopw_reduced <- stopwords("de") %>% 
    stopwords_remove(pattern = c("daß", "zu")) 
```

**Comment by kbenoit** [comment]
Interesting idea. This could directly follow `tokens_select/remove()` and be:
```r
char_select(x, pattern, selection = c("keep", "remove"),
  valuetype = c("glob", "regex", "fixed"), case_insensitive = TRUE,
  padding = FALSE, min_nchar = 1L, max_nchar = 79L,
  verbose = quanteda_options("verbose"))
```
No new function needed for adding, since we already have `c()`.

@koheiw what do you think?

**Comment by stefan-mueller** [comment]
Great idea, @kbenoit. With a **quanteda** implementation of `char_select` (plus `char_keep` and `char_remove`) users could easily customise stopword lists.

**Comment by kbenoit** [comment]
How about this:

```r
stopwords_edit <- function(x) {
  tfile <- tempfile(fileext = ".yml")
  yaml::write_yaml(x, file = tfile)
  try(edited <- utils::edit(file = tfile), silent = TRUE)
  yaml::read_yaml(tfile)
}

# edit and save just the vector
newru <- stopwords_edit(stopwords("ru"))

# edit the whole list
newmisc <- stopwords_edit(data_stopwords_snowball)
```

**Comment by stefan-mueller** [comment]
That's a very cool solution! But this implementation is not very transparent/reproducible because the selection happens manually. It might be good to (also) make changes without using the editor (for example).:
- `stopwords_edit(stopwords("en"), -c("will")) # remove "will"`
- `stopwords_edit(stopwords("de"), c("dass")) # add "dass"`

Or we keep `stopwords_edit()` as it stands and also create `stopwords_add`() and `stopwords_remove()` for manual edits?

**Comment by kbenoit** [comment]
I like having all three.

```r
stopwords_edit(x)
stopwords_add(x, y)
stopwords_remove(x, pattern, valuetype = c("glob", "regex", "fixed"))
```
